### ISSUE TITLE
DESIGN: Data collection

### ISSUE THREAD

**Issue by masteryoda123** [zalaby12/amazing-me#20]
list of game results

each has a single milestone, the score for the milestone, problem areas, and the timestamp

**Comment by zalaby12** [comment]
@southgatew @masteryoda123 time to talk about this. I would love backlogs created from this by tomorrow. 

a general idea of a class we can create is good enough but i want us to have talked through it.

**Comment by masteryoda123** [comment]
@zalaby12 i think this is done since we know what we're storing already?
