### ISSUE TITLE
Login + Registration: Dialog Box for Login Success/Failure

### ISSUE THREAD

**Issue by masteryoda123** [zalaby12/amazing-me#42]
UI should give user feedback for success/failure in a form of a dialog box

@DKim0509 and @VernBuck what's the status on this? how easy is it? if you can show me examples i'll work with you on it to make it modular.

**Comment by zalaby12** [comment]
hey @masteryoda123 when you finish this can you make another backlog and use the same concept to create a quick terms of agreement pop-up after registration. that should actually be HIGH priority and i really don't want us to forget about it. 

but only when you've figured out how to generalize the process

**Comment by zalaby12** [comment]
@masteryoda123 is this done??
