### ISSUE TITLE
Child Details Setup Page

### ISSUE THREAD

**Issue by zalaby12** [zalaby12/amazing-me#48]
First Name
Last Name
age
sex (not gender... don't put gender) (dropdown)
a way to insert picture ( @southgatew @masteryoda123 @DKim0509 @VernBuck can we do research on this? please? i'd like to have an idea of what we are getting ourselves into.)
drop down for "known disabilities"
    if yes selected -> another dropdown to put in the name
    if no selected  -> nothing

"add another child" button
"Done!" button

anything else??

**Comment by masteryoda123** [comment]
@zalaby12 did you finish this?
